### ISSUE TITLE
Remove tab characters

### ISSUE THREAD

**Issue by jmferreiratech** [LaNoC-UFC/rsbr#51]
Convert all tabs to 4-spaces.

**Comment by jmferreiratech** [comment]
@erodac, @leonelmaia, @GustavoCig, @matheus220 , @rmilfont and @rafaelgmota, That's why I'm going to do it: http://www.javapractices.com/topic/TopicAction.do?Id=244.
So please, configure your favorite IDE to map TAB keys to 4-spaces.

**Comment by rmilfont** [comment]
Hey guys (@erodac, @leonelmaia, @GustavoCig, @matheus220 , @rafaelgmota ), if you use IntelliJ IDE,  follow the below steps:
Open the "Default settings" dialog by navigating to File-> Other Settings. Navigate to Code Style->Java. The Tab size is configurable on that pane. After this, just click on "Apply" and "Ok" at the end.
