### ISSUE TITLE
Fix some unity tests at FaultyGraphSegmentationTest

### ISSUE THREAD

**Issue by rmilfont** [LaNoC-UFC/rsbr#56]
Fix faulty3x3Graph and faultyGraph unity tests on tests/FaultyGraphSegmentationTest.

**Comment by jmferreiratech** [comment]
Everything is working like a charm here. Could you please double check it?

**Comment by rmilfont** [comment]
Sorry! My commit for issue #58 is breaking these two tests. I will work on it.

**Comment by rmilfont** [comment]
Done. Everything is ok now.

**Comment by jmferreiratech** [comment]
Fine.
