### ISSUE TITLE
Fix empty range 'indexing' behavior

### ISSUE THREAD

**Issue by matheus220** [LaNoC-UFC/rsbr#93]
Modify Region.outsiders() to work with regions without destinations.

**Comment by jmferreiratech** [comment]
Region.outsiders() breaks when it accesses min/max of the EMPTY Range. So, IMO the change has to be made at Range.

**Comment by rafaelgmota** [comment]
assign to me

**Comment by jmferreiratech** [comment]
You should remove the "ignore" annotation from [here](https://github.com/LaNoC-UFC/rsbr/blob/develop/tests/rbr/AdjustRegionsTest.java#L43) once it's fixed.
